package cornare

type MunicipioInfo struct {
	Municipio string
	Region    string
}

var municipiosOrienteAntioqueno = []string{
	"Abejorral",
	"Alejandría",
	"Argelia",
	"Concepción",
	"El Carmen de Viboral",
	"El Peñol",
	"El Retiro",
	"El Santuario",
	"Granada",
	"Guarne",
	"Guatapé",
	"La Ceja",
	"La Unión",
	"Marinilla",
	"Nariño",
	"Puerto Triunfo",
	"Rionegro",
	"San Carlos",
	"San Francisco",
	"San Luis",
	"San Rafael",
	"San Roque",
	"San Vicente Ferrer",
	"Santo Domingo",
	"Sonsón",
}

var stationMunicipios = map[string]MunicipioInfo{
	"49":  {"San Rafael", "Bosques"},
	"2":   {"El Santuario", "Valle de San Nicolás"},
	"5":   {"Rionegro", "Valle de San Nicolás"},
	"201": {"Rionegro", "Valle de San Nicolás"},
	"212": {"Rionegro", "Valle de San Nicolás"},
	"48":  {"Rionegro", "Valle de San Nicolás"},
	"405": {"San Francisco", "Bosques"},
	"320": {"Alejandría", "Bosques"},
	"43":  {"San Francisco", "Bosques"},
	"308": {"San Roque", "Porce Nus"},
	"50":  {"San Rafael", "Bosques"},
	"6":   {"Rionegro", "Valle de San Nicolás"},
	"309": {"Alejandría", "Porce Nus"},
	"202": {"Rionegro", "Valle de San Nicolás"},
	"208": {"Rionegro", "Valle de San Nicolás"},
	"401": {"Rionegro", "Valle de San Nicolás"},
	"213": {"Rionegro", "Valle de San Nicolás"},
	"204": {"Rionegro", "Valle de San Nicolás"},
	"317": {"El Carmen de Viboral", "Valle de San Nicolás"},
	"205": {"Rionegro", "Valle de San Nicolás"},
	"207": {"Rionegro", "Valle de San Nicolás"},
	"206": {"Rionegro", "Valle de San Nicolás"},
	"9":   {"Guarne", "Valle de San Nicolás"},
	"42":  {"Santo Domingo", "Porce Nus"},
	"209": {"Rionegro", "Valle de San Nicolás"},
	"302": {"El Retiro", "Valle de San Nicolás"},
	"304": {"La Unión", "Valle de San Nicolás"},
	"312": {"Nariño", "Páramo"},
	"314": {"Granada", "Aguas"},
	"8":   {"Guarne", "Valle de San Nicolás"},
	"7":   {"Guarne", "Valle de San Nicolás"},
	"41":  {"Abejorral", "Páramo"},
	"301": {"El Carmen de Viboral", "Valle de San Nicolás"},
	"44":  {"El Carmen de Viboral", "Valle de San Nicolás"},
	"10":  {"El Carmen de Viboral", "Valle de San Nicolás"},
	"403": {"La Ceja", "Valle de San Nicolás"},
	"11":  {"La Ceja", "Valle de San Nicolás"},
	"15":  {"El Retiro", "Valle de San Nicolás"},
	"16":  {"Puerto Triunfo", "Bosques"},
	"18":  {"Puerto Triunfo", "Bosques"},
	"39":  {"La Unión", "Valle de San Nicolás"},
	"20":  {"Nariño", "Páramo"},
	"13":  {"El Retiro", "Valle de San Nicolás"},
	"14":  {"El Retiro", "Valle de San Nicolás"},
	"37":  {"Marinilla", "Valle de San Nicolás"},
	"30":  {"Santo Domingo", "Porce Nus"},
	"32":  {"El Retiro", "Valle de San Nicolás"},
	"26":  {"Puerto Triunfo", "Bosques"},
	"28":  {"San Carlos", "Aguas"},
	"24":  {"Guarne", "Valle de San Nicolás"},
	"29":  {"San Roque", "Porce Nus"},
	"33":  {"El Retiro", "Valle de San Nicolás"},
	"23":  {"Guarne", "Valle de San Nicolás"},
	"27":  {"San Vicente Ferrer", "Valle de San Nicolás"},
	"31":  {"Marinilla", "Valle de San Nicolás"},
	"22":  {"El Carmen de Viboral", "Valle de San Nicolás"},
	"25":  {"El Retiro", "Valle de San Nicolás"},
	"21":  {"San Luis", "Bosques"},
	"51":  {"Argelia", "Páramo"},
	"211": {"Rionegro", "Valle de San Nicolás"},
	"47":  {"Rionegro", "Valle de San Nicolás"},
	"40":  {"Concepción", "Porce Nus"},
	"52":  {"El Retiro", "Valle de San Nicolás"},
	"34":  {"La Ceja", "Valle de San Nicolás"},
	"35":  {"La Ceja", "Valle de San Nicolás"},
	"36":  {"El Santuario", "Valle de San Nicolás"},
	"38":  {"San Roque", "Porce Nus"},
}
